name: Pre CD with EB and RDS Test env

on:
  pull_request:
    branchs: [ master ]

jobs:
  test-pre-cd:
    runs-on: ubuntu-latest

    strategy:
      maxtrix:
        node-version: [12.x]

    steps:
    - name: Configure AWS credentials from Test Environment
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: start rds postgres test database
      run: aws rds start-db-instance --db-instance-identifier pg-test-env --region us-east-2
    
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm testcd

    
